// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1891.FirstSteamworks.commands;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.PIDCommand;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc1891.FirstSteamworks.Robot;

/**
 *
 */
public class Align extends Command{

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	
	// For debug, prints auto only.
	public static boolean autoPrint = false;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	double center;
	boolean targetSpotted;
	boolean reinitialized = false;
	boolean alignStarted = false;
	boolean yIsFinished = false;
	boolean xIsFinished = false;
	double error;
	
	//PID values for side to side alignment
	private static final double m_XkP = 0.003;
	private static final double m_XkI = 0;
	private static final double m_XkD = 0;
	static final double m_acceptableErrorX = 5;
	private static final double min_Output = 0.2;
	
	//PID values for forward backward alignment
	private static final double m_YkP = 0.0001;
	private static final double m_YkI = 0;
	private static final double m_YkD = 0;
	static final double m_acceptableErrorY = 300;
	
	private PIDController m_controllerX;
	private PIDController m_controllerY;
	
	private double m_xOutput;
	private double m_yOutput;
	
	private final PIDOutput m_outputX = this::usePIDOutputX;
	private final PIDOutput m_outputY = this::usePIDOutputY;
	
	private final PIDSource m_sourceX = new PIDSource() {
	    public void setPIDSourceType(PIDSourceType pidSource) {
	    }

	    public PIDSourceType getPIDSourceType() {
	      return PIDSourceType.kDisplacement;
	    }

	    public double pidGet() {
	      return returnPIDInputX();
	    }
	};
	  
	private final PIDSource m_sourceY = new PIDSource() {
		public void setPIDSourceType(PIDSourceType pidSource) {
		}

		public PIDSourceType getPIDSourceType() {
			return PIDSourceType.kDisplacement;
		}

		public double pidGet() {
			return returnPIDInputY();
		}
	};
	
    /**
     * 
     */
    public Align() {
    	super(0.4);
    	requires(Robot.driveSystem);
    	requires(Robot.camera);
    	requires(Robot.gearCarrier);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	
    	m_controllerX = new PIDController(m_XkP, m_XkI, m_XkD, m_sourceX, m_outputX);
//    	m_controllerY = new PIDController(m_YkP, m_YkI, m_YkD, m_sourceY, m_outputY);
    	m_controllerX.setInputRange(-160, 160);
    	m_controllerX.setOutputRange(-0.3, 0.3);
//    	m_controllerY.setInputRange(0, 24);
//    	m_controllerY.setOutputRange(-0.2, 0.2);
    	m_controllerX.setAbsoluteTolerance(m_acceptableErrorX);
//    	m_controllerY.setAbsoluteTolerance(m_acceptableErrorY);
    	m_controllerX.setToleranceBuffer(5);
//    	m_controllerY.setToleranceBuffer(5);
    	m_controllerX.setSetpoint(0);
//    	m_controllerY.setSetpoint(0);
    	
//    	m_controllerY.enable();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if (!reinitialized) {
    		System.out.println("Align Started");
    		setTimeout(0.2);
    		Robot.driveSystem.setVelocityMode();
    		m_controllerX.enable();
    		reinitialized = true;
    	}
//    	try {
//			error = Robot.camera.getPegTargetPositionError();
//		} catch (NoTargetFoundException e) {
//			e.printStackTrace();
//		}
//    	
//    	SmartDashboard.putNumber("error", error);
//    	
//    	if(error > m_acceptableError || error < -m_acceptableError)
//    	{
//    		SmartDashboard.putNumber("power", error * m_P);
//    		Robot.driveSystem.driveSideways(error * m_P);
//    	}
//    	else if(error < m_acceptableError && error > -m_acceptableError && error != 0)
//    	{
//    		
//    		isFinished = true;
//    		error = 0;
//    	}
//    	if (m_controllerX.getError() < 10 || m_controllerY.getError() > -10) {
//    		m_controllerY.enable();
//    		System.out.println("y enabled");
//    	}
    	
//    	xIsFinished = m_controllerX.onTarget();
//    	
//    	if (xIsFinished) {
//    		m_controllerX.disable();
//    		System.out.println("x disabled");
//    	}
    	
//    	SmartDashboard.putNumber("align x error", m_controllerX.getError());
//    	SmartDashboard.putNumber("align y error", m_controllerY.getError());
//    	SmartDashboard.putNumber("align x output", m_xOutput);
//    	SmartDashboard.putNumber("align y output", m_yOutput);
    	
    	System.out.println("Align x error: " + m_controllerX.getError());
		System.out.print(" Align x output: "+ m_xOutput);
    	
//    	if (!this.autoPrint) {
//    		
////    		System.out.print(" Align y error: "+ m_controllerY.getError());
////    		System.out.print(" Align y output: "+ m_yOutput);
//    	}
//    	SmartDashboard.putNumber("power", m_controllerX.get());
//    	SmartDashboard.putNumber("error", m_controllerY.getError());
//    	SmartDashboard.putNumber("power", m_controllerY.get());
//    	System.out.println("output" + m_xOutput);
    	if (!Robot.camera.isTargetSighted()) {
    		m_xOutput = -m_xOutput;
    	}
    	else if (alignStarted || this.isTimedOut()) {
    		Robot.driveSystem.vectorDrive(-m_xOutput, 0/*m_yOutput*/);
    		alignStarted = true;
    	}
    	else {
    		Robot.driveSystem.vectorDrive(0, 0);
    	}
    	//image is 640px wide and 480px tall
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
//    	if (alignStarted && m_controllerX.onTarget()) {
//    		this.setTimeout(0.5);
//    	}
//    	else if (m_controllerX.)
        return (m_controllerX.onTarget() && alignStarted /* && m_controllerY.onTarget()) || Robot.gearCarrier.inPosition(*/);
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.driveSystem.stopMotors();
		m_controllerX.reset();
    	reinitialized = false;
    	System.out.println("Align finished");
    	autoPrint = true;
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
	
	protected double returnPIDInputX() {
		return Robot.camera.getErrorX();
	}

	protected double returnPIDInputY() {
		return Robot.camera.getErrorY();
	}
	
	protected void usePIDOutputX(double output) {
//		if (xIsFinished) {
//			m_xOutput = 0;
//		}
//		else {
		if (m_xOutput < min_Output && m_xOutput > 0) {
			m_xOutput = min_Output;
		}
		else if (m_xOutput > -min_Output && m_xOutput < 0) {
			m_xOutput = -min_Output;
		}
		else {
			m_xOutput = output;
		}
			
//		}
	}
	
	protected void usePIDOutputY(double output) {
//		if (!yIsStarted || yIsFinished) {
//			m_yOutput = 0;
//		}
//		else {
//			m_yOutput = output;
//		}
	}
}
