// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1891.FirstSteamworks.commands;
import edu.wpi.first.wpilibj.command.TimedCommand;
import org.usfirst.frc1891.FirstSteamworks.Robot;

/**
 *
 */
public class DriveForwardVelocity extends TimedCommand {

	private double m_speed;
	
    /**
     * Drives straight forward or backward, without turning or moving sideways
     * @param speed target wheel speed in rotations per second. 
     */
    public DriveForwardVelocity(int speed) {
    	super(2);
        requires(Robot.driveSystem);
        m_speed = speed;
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.driveSystem.setVelocityMode();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	Robot.driveSystem.setFrontLeftWheel(m_speed);
    	Robot.driveSystem.setRearLeftWheel(m_speed);
    	Robot.driveSystem.setFrontRightWheel(m_speed);
    	Robot.driveSystem.setRearRightWheel(m_speed);
    	Robot.driveSystem.publishSpeeds();
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.driveSystem.stopMotors();
    	Robot.driveSystem.setPercentageMode();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
